AMovie = input("Name a movie: ")
aSnack = input("Name a type of snack: ")
aTheater = input("Name a movie theater: ")
aCity = input("Name a city: ")
print("You can't wait to see",AMovie, "while eating", aSnack, "In a theater called", aTheater, "watching it in", aCity)
